# Generated by Django 2.0.7 on 2018-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='albumcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='albumphotos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='memberintroducerreference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordercart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderprocess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postattachmenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receivemethod',
            options={},
        ),
    ]
