# Generated by Django 2.0.7 on 2018-08-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180810_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='albumimage',
            options={'managed': False},
        ),
    ]
