# Generated by Django 2.0.7 on 2018-08-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180810_2138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='albumimage',
            table='album_image',
        ),
    ]
