# Generated by Django 2.0.7 on 2018-08-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180810_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': False, 'verbose_name': '相簿', 'verbose_name_plural': '相簿'},
        ),
        migrations.AlterModelOptions(
            name='albumimage',
            options={'managed': False, 'verbose_name': '相簿照片', 'verbose_name_plural': '相簿照片'},
        ),
    ]
