# Generated by Django 2.0.7 on 2018-08-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180811_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('redirect_uris', models.TextField()),
                ('client_type', models.CharField(max_length=32)),
                ('authorization_grant_type', models.CharField(max_length=32)),
                ('client_secret', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('skip_authorization', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('revoked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_provider_refreshtoken',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False, 'verbose_name': '活動', 'verbose_name_plural': '活動'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False, 'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': '訂單', 'verbose_name_plural': '訂單'},
        ),
        migrations.AlterModelOptions(
            name='ordercart',
            options={'managed': False, 'verbose_name': '購買項目', 'verbose_name_plural': '購買項目'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False, 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
